### ISSUE TITLE
Issue genarating fake data for employee table

### ISSUE THREAD

**Issue by fvgm-spec** [necatiarslan/table-faker#1]
As I have set the configuration of the Jupyter Notebook to take the schema definition YAML file to generate only the `person` fake data table, then the CSV file is successfully created.

![tablkefaker_person_test1](https://github.com/necatiarslan/table-faker/assets/60470663/4c6cb4a2-bf57-4c77-bd71-c1f8edd90e73)
![tablkefaker_person_test2](https://github.com/necatiarslan/table-faker/assets/60470663/8bc6eb9e-17f8-4c5b-ae48-6ab709836636)
[person_2023-12-14_13-17-54-039878.csv](https://github.com/necatiarslan/table-faker/files/13675798/person_2023-12-14_13-17-54-039878.csv)

However, once I include in the YAML file the definition schema to generate both tables  `person`  and  `employee`, I get the following error:

`AttributeError: 'Generator' object has no attribute 'school_name'`

Find attached screenshots:

![tablkefaker_employee_test1](https://github.com/necatiarslan/table-faker/assets/60470663/b6e4e823-ab57-4434-b70e-897161b221fd)
![tablkefaker_employee_test2](https://github.com/necatiarslan/table-faker/assets/60470663/215a5d3a-4315-4e42-9ef0-f5bef5145ba1)

**Comment by necatiarslan** [comment]
Hi, thank you for trying Table Faker.
This is an expected case. school_name is in another custom faker provider; you should add it like below.
With this example, I want to show how you can also use custom faker providers.
You can delete the school column and try again if you want.

You can use a custom faker provider

```
from faker_education import SchoolProvider

tablefaker.to_csv("test_table.yaml", "./target_folder", fake_provider=SchoolProvider)
```

multiple custom provider in list also works

**Comment by necatiarslan** [comment]
It should fail for level column as well because it uses a function called get_level.
you should provide this function as well like below.

```
from tablefaker import tablefaker
from faker import Faker

fake = Faker()
def get_level():
    return f"level {fake.random_int(1, 5)}"

tablefaker.to_csv("test_table.yaml", "./target_folder", custom_function=get_level)
```

**Comment by fvgm-spec** [comment]
Great Necati, thanks for your quick response. I am gonna give a second try by adding those parameters, and also test another feature. It would be great to add those test cases to the documentation.

Keep in touch!
